//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string AppointmentDesc { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string AppointmentName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> AppointmentOn { get; set; }
        public Nullable<int> AttendId { get; set; }
    }
}
