//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmedEmail
    {
        public int ConfirmEmailId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string GUId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
