//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailLog
    {
        public long Maillogid { get; set; }
        public string MailBody { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> SentbyId { get; set; }
        public Nullable<bool> Issent { get; set; }
    }
}
