//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordHistory
    {
        public long PasswordHistoryId { get; set; }
        public string Password { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
