//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPatientIndexDevEntities : DbContext
    {
        public MasterPatientIndexDevEntities()
            : base("name=MasterPatientIndexDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<ArticleContent> ArticleContents { get; set; }
        public virtual DbSet<ArticleSubTitle> ArticleSubTitles { get; set; }
        public virtual DbSet<ArticleTitle> ArticleTitles { get; set; }
        public virtual DbSet<ConfirmedEmail> ConfirmedEmails { get; set; }
        public virtual DbSet<HospitalEHRSystem> HospitalEHRSystems { get; set; }
        public virtual DbSet<Hosptial> Hosptials { get; set; }
        public virtual DbSet<MailLog> MailLogs { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonToPerson> PersonToPersons { get; set; }
        public virtual DbSet<Physician> Physicians { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Seminar> Seminars { get; set; }
        public virtual DbSet<SeminarData> SeminarDatas { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<UserProgress> UserProgresses { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
    }
}
