//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.PersonToPersons = new HashSet<PersonToPerson>();
            this.PersonToPersons1 = new HashSet<PersonToPerson>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SessionToken { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public int Phone1 { get; set; }
        public Nullable<int> Phone2 { get; set; }
        public Nullable<int> Phone3 { get; set; }
        public int PersonIsPatient { get; set; }
        public bool AcknowledgedNoticeOfPrivacy { get; set; }
        public string Address { get; set; }
        public int ZipCode { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Procedure { get; set; }
        public Nullable<System.DateTime> ProcedureDate { get; set; }
        public string InsuranceCompanyName { get; set; }
        public System.DateTime InsuranceEffectiveDate { get; set; }
        public string Guarantor { get; set; }
        public string GroupNumber { get; set; }
        public string PolicyNumber { get; set; }
        public string PreferredPharmacy { get; set; }
        public string PharmacyPhone { get; set; }
        public string PharmacyAddress1 { get; set; }
        public string PharmacyAddress2 { get; set; }
        public string PharmacyCity { get; set; }
        public string PharmacyState { get; set; }
        public Nullable<bool> ConfirmedByEmail { get; set; }
        public string address1 { get; set; }
        public Nullable<int> CareGiver { get; set; }
        public Nullable<bool> active { get; set; }
        public string profileimage { get; set; }
        public string maritalstatus { get; set; }
        public string Weight { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> preferredcommunicationmobile { get; set; }
        public string SocialNetworks { get; set; }
        public string Language { get; set; }
        public string country { get; set; }
        public string relationship { get; set; }
        public Nullable<int> roleid { get; set; }
        public string caregivercomment { get; set; }
        public Nullable<bool> preferredcommunicationemail { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> approuvedate { get; set; }
        public Nullable<int> blockcount { get; set; }
        public Nullable<System.DateTime> atemptdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonToPerson> PersonToPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonToPerson> PersonToPersons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
