//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar
    {
        public long id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> seminardate { get; set; }
        public string email { get; set; }
        public Nullable<int> seminarid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> isview { get; set; }
        public Nullable<System.DateTime> registerdate { get; set; }
    }
}
