//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public long Id { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    }
}
